 # --- !Ups
CREATE TABLE "CONTACTS" (
  "ID" BIGSERIAL NOT NULL PRIMARY KEY,
  "FULLNAME" VARCHAR(255) NOT NULL,
  "NUMBER" VARCHAR(255) NOT NULL
);

CREATE TABLE "USER_BANKS" (
  "ID" BIGSERIAL NOT NULL PRIMARY KEY,
  "ID_USER" BIGINT NOT NULL,
  "BANK_NAME" VARCHAR(255) NOT NULL,
  "BRANCH" VARCHAR(255) NOT NULL,
  "ACCT_TYPE" VARCHAR(255) NOT NULL,
  "ACCT_NUMBER" VARCHAR(255) NOT NULL,
  "ACCT_OWNER" VARCHAR(255) NOT NULL,
  "STATUS" SMALLINT NOT NULL
);


 # --- !Downs
DROP TABLE "CONTACTS";
DROP TABLE "USER_BANKS";



